version: '3'
services:
  citadels-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: citadels-backend-image
    environment:
      - MONGO_URI=${MONGO_URI}
    ports:
      - 8080:8080
    depends_on:
      - mongo-db
  mongo-db:
    image: mongo
    ports:
      - 27017:27017
