name: Java CICD
on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        working-directory: packages/backend/
        run: mvn package -DskipTests

      - name: Move JAR and Dockerfile to workspace
        run: |
          mv packages/backend/spring/target/citadels-backend-0.0.1-SNAPSHOT.jar $GITHUB_WORKSPACE/citadels-backend-0.0.1-SNAPSHOT.jar
          mv packages/backend/spring/Dockerfile $GITHUB_WORKSPACE/Dockerfile
          rm -rf packages docs README.md    

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}/backend

      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /webApp/backend 
            sudo docker rmi citadels-backend-image
            sudo docker stop citadels-backend
            sudo docker rm citadels-backend
            sudo docker build -t citadels-backend-image .
            sudo docker run --name citadels-backend -d -p 8080:8080 citadels-backend-image 
