name: backend pr ci job

on:
  push:
    branches: [ "backend/tes_backend_cd" ]
    paths: 
      - 'packages/backend/**'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn test
      working-directory: packages/backend/