name: E2E Tests

on:
  pull_request:
    branches: [ "main" ]
    paths: 
      - 'packages/frontend/**'

jobs:
  test:
    runs-on: ubuntu-latest  # 使用 Ubuntu 環境

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # 檢查代碼庫

      - name: Install dependencies
        run: npm ci  # 安裝相依套件
        working-directory: packages/frontend/

      - name: Run Cypress tests
        run: | 
          npm run dev
          npm run cypress:open  # 執行 Cypress 測試
        working-directory: packages/frontend/
